### ISSUE TITLE
Print speed setting greyed out

### ISSUE THREAD

**Issue by evilC** [Snapmaker/SnapmakerJ1CuraPlugin#30]
I think this is similar to #25 (Probably same root cause) - basically it seems that a load of stuff is set in the printer profiles, and when this is done, you cannot override the setting in custom profiles

Repro:

1. Select `Fast - 0.2mm` profile
2. Change any value in the settings
3. Open the profiles dropdown list
4. Click `Create profile from current settings / overrides`
5. Name the new profile (In my screenshot, I used `Default 100mm/s`
6. In your new profile, certain values are not changeable (In the screenshot, `Print Speed` is locked at `200`)

![image](https://user-images.githubusercontent.com/1719428/207415275-0ca3d4cc-760e-4c02-8ebf-8db167b27b01.png)

I am not 100% sure if this actually stops me from being able to do what I need, I can change infill speed and wall speed, it's just annoying. With my Ender 3 profile, this setting is not disabled, and when I edit `Print Speed`, it changes `Infill Speed` to the entered value, and `Wall speed` to 50% of the entered value.

**Comment by parachvte** [comment]
In J1, speeds in our profiles vary a lot. Nearly every speed has a different value, the value bindings are disabled. The goal of our J1 plugin is to provide open-to-use parameters to end users, so parameters are tuned by our engineers, value bindings doesn't work in our way.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/3749551/208403836-9191eacc-0e9d-48e8-9b09-6683683ecf9b.png">
