### ISSUE TITLE
Temp and retraction values

### ISSUE THREAD

**Issue by hiltpatr** [Snapmaker/SnapmakerJ1CuraPlugin#38]
The temperature for PETG is only set to 215 which is really low. Also retraction distance is set to 6.5 which is really high for direct drive. These values are causing a lot of issues from the 0.2.1 build. This 0.5 build has made the quality mush worse on prints and I get a lot more skipping in the extruders.

**Comment by parachvte** [comment]
You could use our pre-defined Snapmaker materials (with 1.5mm retraction defined)

**Comment by hiltpatr** [comment]
Thank you. I found that shortly after posting and closed the request. Sorry
for the confusion.
